# Generated by Django 5.1.5 on 2025-01-19 04:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000000', max_length=128, region=None),
        ),
    ]
